// Siyo Farms - Central product data store

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number;
  originalPrice?: number;
  unit: string;
  description: string;
  longDescription: string;
  badge?: string;
  inStock: boolean;
  featured: boolean;
  emoji: string;
  tags: string[];
  benefits: string[];
}

export const products: Product[] = [
  // MILK
  {
    id: "p1",
    slug: "a2-gir-cow-milk",
    name: "A2 Gir Cow Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 75,
    unit: "500ml",
    description: "Pure A2 milk from indigenous Gir cows. Rich in A2 beta-casein protein.",
    longDescription: "Our A2 Gir Cow Milk comes from certified Gir cows raised on natural grass and organic feed. Rich in A2 beta-casein protein, it is easier to digest than regular milk. No hormones, no antibiotics, no preservatives.",
    badge: "Best Seller",
    inStock: true,
    featured: true,
    emoji: "🐄",
    tags: ["a2", "gir", "cow", "pure"],
    benefits: ["Easy to digest", "Rich in A2 protein", "No hormones", "Ethically sourced"],
  },
  {
    id: "p2",
    slug: "buffalo-milk",
    name: "Buffalo Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 65,
    unit: "500ml",
    description: "Thick, creamy buffalo milk. High fat content, perfect for making sweets.",
    longDescription: "Our fresh buffalo milk is collected daily from healthy buffaloes. With naturally high fat content, it is ideal for making rich kheer, gulab jamun, and other Indian sweets. Delivered fresh every morning.",
    badge: "Fresh Daily",
    inStock: true,
    featured: true,
    emoji: "🦬",
    tags: ["buffalo", "creamy", "fresh"],
    benefits: ["High fat content", "Great for sweets", "Collected daily", "No additives"],
  },
  {
    id: "p3",
    slug: "high-protein-milk",
    name: "High Protein Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 90,
    originalPrice: 110,
    unit: "500ml",
    description: "Fortified with extra protein. Perfect for fitness enthusiasts and growing children.",
    longDescription: "Siyo Farms High Protein Milk is specially formulated for fitness lovers, athletes, and growing children. Contains 50% more protein than regular milk. No artificial additives – just natural milk fortified the right way.",
    badge: "Sale",
    inStock: true,
    featured: true,
    emoji: "💪",
    tags: ["protein", "fitness", "fortified"],
    benefits: ["50% more protein", "Great for athletes", "Kids-friendly", "Natural fortification"],
  },
  {
    id: "p4",
    slug: "lactose-free-milk",
    name: "Lactose Free Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 85,
    unit: "500ml",
    description: "All the goodness of milk without lactose. Perfect for lactose-intolerant individuals.",
    longDescription: "Our Lactose Free Milk undergoes a special enzymatic process that breaks down lactose into simpler sugars. You get all the calcium, vitamins, and proteins of regular milk without the discomfort.",
    badge: "New",
    inStock: true,
    featured: false,
    emoji: "🥛",
    tags: ["lactose-free", "sensitive", "digestive"],
    benefits: ["No lactose discomfort", "Full nutrition", "Easy digest", "Same great taste"],
  },
  {
    id: "p5",
    slug: "toned-milk",
    name: "Toned Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 50,
    unit: "500ml",
    description: "Low-fat toned milk for everyday use. Light on calories, rich in nutrients.",
    longDescription: "Siyo Farms Toned Milk is perfect for health-conscious families. Reduced fat content while maintaining full nutritional value. Ideal for tea, coffee, cereals and everyday drinking.",
    inStock: true,
    featured: false,
    emoji: "🍼",
    tags: ["toned", "low-fat", "everyday"],
    benefits: ["Low fat", "Daily use", "Rich in calcium", "Affordable"],
  },
  {
    id: "p6",
    slug: "raw-cow-milk",
    name: "Raw Cow Milk",
    category: "Milk",
    categorySlug: "milk",
    price: 60,
    unit: "500ml",
    description: "Unprocessed raw cow milk with all natural enzymes intact.",
    longDescription: "For those who prefer their milk completely natural, our Raw Cow Milk is collected fresh, cold-processed and delivered within hours. All natural enzymes and beneficial bacteria are intact.",
    badge: "Pure",
    inStock: true,
    featured: false,
    emoji: "🌿",
    tags: ["raw", "natural", "enzymes"],
    benefits: ["All enzymes intact", "Unprocessed", "Natural bacteria", "Traditional taste"],
  },
  // GHEE
  {
    id: "p7",
    slug: "a2-gir-cow-ghee",
    name: "A2 Gir Cow Ghee",
    category: "Ghee",
    categorySlug: "ghee",
    price: 850,
    originalPrice: 950,
    unit: "500g",
    description: "100% pure A2 ghee made with traditional bilona method. Golden, aromatic and nutritious.",
    longDescription: "Our A2 Gir Cow Ghee is made using the traditional bilona (hand-churned) method from pure A2 cow milk curd. The slow process preserves all nutrients including Omega-3, vitamins A, D, E and K. Rich golden color and divine aroma.",
    badge: "Premium",
    inStock: true,
    featured: true,
    emoji: "🫙",
    tags: ["ghee", "a2", "bilona", "premium"],
    benefits: ["Traditional bilona method", "Rich in Omega-3", "All vitamins intact", "Golden aroma"],
  },
  {
    id: "p8",
    slug: "buffalo-ghee",
    name: "Buffalo Ghee",
    category: "Ghee",
    categorySlug: "ghee",
    price: 650,
    unit: "500g",
    description: "Rich, aromatic buffalo ghee. High smoke point, ideal for cooking and tempering.",
    longDescription: "Buffalo Ghee from Siyo Farms is made from fresh buffalo milk cream. Its high smoke point makes it perfect for deep frying, sauteing, and tempering. Dense and richly flavored.",
    inStock: true,
    featured: false,
    emoji: "✨",
    tags: ["buffalo", "ghee", "cooking"],
    benefits: ["High smoke point", "Dense texture", "Great for cooking", "Rich flavor"],
  },
  {
    id: "p9",
    slug: "pure-butter",
    name: "Pure White Butter",
    category: "Ghee",
    categorySlug: "ghee",
    price: 200,
    unit: "200g",
    description: "Fresh hand-churned white butter (makhan). No salt, no preservatives.",
    longDescription: "Traditional white butter made fresh from whole cow milk cream. Unsalted, preservative-free, and absolutely natural. Best enjoyed on hot rotis, parathas, and toast.",
    badge: "Fresh",
    inStock: true,
    featured: false,
    emoji: "🧈",
    tags: ["butter", "makhan", "fresh", "unsalted"],
    benefits: ["Hand-churned", "No salt added", "No preservatives", "Fresh daily"],
  },
  // PANEER & CURD
  {
    id: "p10",
    slug: "fresh-paneer",
    name: "Fresh Paneer",
    category: "Paneer & Curd",
    categorySlug: "paneer-curd",
    price: 120,
    unit: "200g",
    description: "Soft, fresh homestyle paneer. Made from full-fat cow milk. Ready to cook.",
    longDescription: "Siyo Farms Paneer is made daily from fresh full-fat cow milk. Soft texture, mild flavor, and incredibly versatile. Perfect for palak paneer, paneer tikka, or eating raw with a sprinkle of salt.",
    badge: "Daily Fresh",
    inStock: true,
    featured: true,
    emoji: "🧀",
    tags: ["paneer", "fresh", "cottage cheese"],
    benefits: ["Made daily", "Full-fat milk", "Soft texture", "No preservatives"],
  },
  {
    id: "p11",
    slug: "dahi-curd",
    name: "Homestyle Dahi",
    category: "Paneer & Curd",
    categorySlug: "paneer-curd",
    price: 60,
    unit: "400g",
    description: "Thick, creamy dahi set in traditional clay pots. Probiotic rich.",
    longDescription: "Our Dahi is set overnight in clay pots using age-old recipes. The result is thick, creamy, slightly tangy curd loaded with natural probiotics. Good for gut health and digestion.",
    badge: "Probiotic",
    inStock: true,
    featured: true,
    emoji: "🏺",
    tags: ["dahi", "curd", "probiotic", "clay pot"],
    benefits: ["Probiotic rich", "Clay pot set", "Thick & creamy", "Gut friendly"],
  },
  {
    id: "p12",
    slug: "kharwas",
    name: "Kharwas (Colostrum Pudding)",
    category: "Paneer & Curd",
    categorySlug: "paneer-curd",
    price: 80,
    unit: "200g",
    description: "Traditional Maharashtrian colostrum milk pudding. Nutritious and delicious.",
    longDescription: "Kharwas is a traditional delicacy made from colostrum milk (the first milk after calving). It is naturally rich in antibodies, proteins, and growth factors. Steamed to a pudding-like consistency – sweet and nutritious.",
    badge: "Traditional",
    inStock: true,
    featured: false,
    emoji: "🍮",
    tags: ["kharwas", "colostrum", "traditional", "maharashtrian"],
    benefits: ["Colostrum rich", "High antibodies", "Traditional recipe", "Seasonal delicacy"],
  },
  {
    id: "p13",
    slug: "shrikhand",
    name: "Shrikhand",
    category: "Paneer & Curd",
    categorySlug: "paneer-curd",
    price: 90,
    originalPrice: 110,
    unit: "200g",
    description: "Creamy, sweetened hung curd. Classic Maharashtrian dessert.",
    longDescription: "Our Shrikhand is made from hung dahi, strained overnight, then sweetened with sugar and flavored with saffron and cardamom. A classic Maharashtrian dessert ready to eat.",
    badge: "Sale",
    inStock: true,
    featured: false,
    emoji: "🍨",
    tags: ["shrikhand", "dessert", "hung curd"],
    benefits: ["Made from hung curd", "Saffron flavored", "No artificial color", "Traditional recipe"],
  },
  // SUBSCRIPTION PACKS
  {
    id: "p14",
    slug: "daily-milk-pack",
    name: "Daily Milk Pack",
    category: "Subscriptions",
    categorySlug: "subscriptions",
    price: 1800,
    originalPrice: 2250,
    unit: "30 days",
    description: "500ml A2 Cow Milk delivered every morning for 30 days. Save 20%.",
    longDescription: "Subscribe to our Daily Milk Pack and get 500ml of fresh A2 Cow Milk delivered every morning. Cancel anytime. Save 20% vs buying daily.",
    badge: "Save 20%",
    inStock: true,
    featured: true,
    emoji: "📅",
    tags: ["subscription", "daily", "monthly"],
    benefits: ["Daily delivery", "Save 20%", "Cancel anytime", "Flexible plans"],
  },
  {
    id: "p15",
    slug: "family-dairy-pack",
    name: "Family Dairy Pack",
    category: "Subscriptions",
    categorySlug: "subscriptions",
    price: 3500,
    originalPrice: 4200,
    unit: "30 days",
    description: "1L milk + 100g butter + 200g dahi every day. Perfect for families.",
    longDescription: "Our Family Dairy Pack includes 1L of fresh A2 Cow Milk, 100g of white butter, and 200g of creamy dahi delivered daily for 30 days. Best value for families.",
    badge: "Best Value",
    inStock: true,
    featured: true,
    emoji: "👨‍👩‍👧‍👦",
    tags: ["family", "subscription", "combo"],
    benefits: ["3 products daily", "Save 17%", "Free delivery", "Customizable"],
  },
];

export const categories = [
  { name: "Milk", slug: "milk", emoji: "🥛", description: "Fresh A2, Buffalo, Protein & More" },
  { name: "Ghee", slug: "ghee", emoji: "🫙", description: "Bilona Ghee, Butter & Cream" },
  { name: "Paneer & Curd", slug: "paneer-curd", emoji: "🧀", description: "Paneer, Dahi, Shrikhand & More" },
  { name: "Subscriptions", slug: "subscriptions", emoji: "📅", description: "Daily, Weekly & Monthly Packs" },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}
